#!/bin/sh
#
# The first test attempts to model the actual running configuration
# that we'll use if we want to keep BuildBot's droppings out of our
# source tree: a symlink to master.cfg in the parent directory.  See
# __init__.py for more details about the reasons for this

set -e

cd .. 
ln -sf bbproto/master.cfg
buildbot create-master

buildbot checkconfig

buildbot start
sleep 1
buildbot reconfig
sleep 1
buildbot stop

# It's also desirable to be able to run checkconfig directly from here
# during development, using an unmodified source tree and adding no
# symlinks, so we'll test again.
echo '#################'

cd bbproto
buildbot checkconfig

